language: android
android:
  components:
    - android-19
    - build-tools-19.1.0
    - extra-google-google_play_services

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
script: ./gradlew clean build
